---
- hosts: server1
  become: yes
  tasks: 
     - name: mariaDb and Bind9
       action: apt name={{ item }} state=installed update_cache=yes
       with_items:
               - mariadb-server
               - bind9
               - python-mysqldb
     
     - name: create database
       mysql_db: name={{ db_name }} state=present
     
     - name: create user
       mysql_user: name={{ db_user }} password={{ db_pass }} priv='{{ db_name }}.*:ALL' host=%

     - name: mysql listen file
       copy: src=./conf/mysql/50-server.cnf dest=/etc/mysql/mariadb.conf.d/50-server.cnf

     - name: bind9 template
       template: src=./conf/bind/db.example.com dest=/var/cache/bind/

     - name: bind9 conf
       template: src=./conf/bind/named.conf.local dest=/etc/bind/
     
     - name: restart services
       service: name={{ item }} state=restarted
       with_items:
               - mariadb
               - bind9


- hosts: server2
  become: yes
  tasks:
          - name: install nginx and fpm
            action: apt name={{ item }} state=installed update_cache=yes
            with_items:
                    - nginx
                    - php7.0
                    - php7.0-fpm
                    - unzip
                    - php-mysql

          - name: copy resolv.conf
            template: src=./conf/resolv/resolv.conf dest=/etc/resolv.conf

          - name: unzip wordpress on web server's directory
            unarchive: src=./conf/wordpress/wordpress-4.9.2.zip dest=/var/www/html

          - name: copy wp-config
            template: src=./conf/wordpress/wp-config.php dest=/var/www/html/wordpress/wp-config.php
  
          - name: change ownership
            file: path=/var/www/html owner=www-data group=www-data state=directory recurse=yes

          - name: nginx's configuration
            copy: src=./conf/nginx/default dest=/etc/nginx/sites-enabled/default

          - name: restart services
            service: name={{ item  }} state=restarted
            with_items:
                    - nginx
                    - php7.0-fpm

          - name: download wp-cli
            get_url: url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar dest=/usr/local/bin/wp mode=a+x
 
          - name: configure wordpress
            shell: sudo -u debian -i -- wp core install --url={{ wp_url }} --title={{ wp_title }} --admin_user={{ wp_admin }} --admin_password={{ wp_pass }} --admin_email=admin@wordpress.com --path=/var/www/html/wordpress 
